### ISSUE TITLE
请问输出的是向量还是结果，是分类器还没加吗

### ISSUE THREAD

**Issue by Youkinnn** [CarryChang/Bert_BaseLine#1]

**Comment by CarryChang** [comment]
分类器加过了，用bert进行向量化，然后向量化之后使用双向LSTM进行分类

**Comment by CarryChang** [comment]
直接输出分类结果

**Comment by CarryChang** [comment]
server是服务端，client.py直接运行就能请求结果了

**Comment by Youkinnn** [comment]
明白了，感谢！

**Comment by aszhanghuali** [comment]
你好，博主，我想请问一下，怎么保存由bert和bilstm提取的特征向量呢？

**Comment by CarryChang** [comment]
bert 是用的谷歌的开放中文向量，BiLSTM 是文本分类模型的特征提取部分，保存的话就直接用 TF 的 model save 保存到本地即可。
